sitename = 'devplayer55221'
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'devplayer55221'
theme = 'hugo-paper'


[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'devplayer55221'               # twitter.com/YOUR_TWITTER_ID
  github = 'devplayer55221'                 # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'mukund-kr-kedia'             # linkedin.com/in/YOUR_LINKEDIN_ID
  # mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  # threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  # bluesky = 'YOUR_BLUESKY_ID'               # https://bsky.app/profile/YOUR_BLUESKY_ID
  # rss = true                                # show rss icon

  # misc
  # disableHLJS = false                        # disable highlight.js
  # disablePostNavigation = true              # disable post navigation
  # monoDarkIcon = false                       # show monochrome dark mode icon
  # math = true                               # enable KaTeX math typesetting globally
  # localKatex = false                        # use local KaTeX js/css instead of CDN
  # favicon = "favicon.ico"                   # customize the default favicon
  # appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
